--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2023. 03. 29. 8:42:03
-- Server version: 5.5.5-10.1.38-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS kosarlabda;

CREATE DATABASE IF NOT EXISTS kosarlabda
	CHARACTER SET utf8
	COLLATE utf8_hungarian_ci;

--
-- Set default database
--
USE kosarlabda;

--
-- Create table `teams`
--
CREATE TABLE IF NOT EXISTS teams (
  id INT(11) NOT NULL AUTO_INCREMENT,
  teamName VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `position`
--
CREATE TABLE IF NOT EXISTS `position` (
  id INT(11) NOT NULL AUTO_INCREMENT,
  posName VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `players`
--
CREATE TABLE IF NOT EXISTS players (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  positionId INT(11) NOT NULL,
  teamId INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

-- 
-- Dumping data for table teams
--
INSERT INTO teams VALUES
(1, 'NY Yankees'),
(2, 'LA Dodgers'),
(3, 'Houston'),
(4, 'Atlanta'),
(5, 'San Diego');

-- 
-- Dumping data for table `position`
--
INSERT INTO `position` VALUES
(1, 'Point guard'),
(2, 'Shooting guard'),
(3, 'Small forward'),
(4, 'Power forward'),
(5, 'Center');

-- 
-- Dumping data for table players
--
-- Table kosarlabda.players does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;